fix node label issue in cluster-configuration start & stop
microsoft/pai pull request #5229
Opened 2021-01-07 03:40 UTC by suiguoxin

2021-01-08 03:34 UTC, hzy46 approved these changes

2021-01-08 05:26 UTC, Binyang2014 requested changes
Please make sure not remove the label when updating the service

2021-01-08 06:51 UTC, Binyang2014 reviewed
Please provide the test results after change the installation config

2021-01-08 06:56 UTC, Binyang2014 approved these changes

2021-01-08 09:31 UTC, hzy46 approved these changes

2021-01-10 08:00 UTC, Binyang2014 approved these changes

2021-01-11 04:26 UTC, merged